name: flutter_kit_demo
description: A demo application showcasing the Flutter Kit package components.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_kit:
    path: ../

  flutter_screenutil: ^5.7.0
  get: ^4.6.5
  dio: ^5.3.2
  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
